### ISSUE TITLE
Semantics of markExperimentPoint

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/educational-experiment-client#152]
[This is an issue that Dhrushit brought up in Derek's L@S paper - this happened with Battleship Numberline]

markExperimentPoint really means 2 things:

1. the student reached a particular point in the code
2. if there is an active experiment for this experiment point and the student is eligible for the experiment, then the student got the assigned condition (meaning the student is "in" the experiment) or the student got "default" (meaning the student is out of the experiment)

In the case of a permanent experiment point, the first bit is accomplished by calling markExperimentPoint at the appropriate place in the code. This call doesn't need to (and shouldn't need to) know whether a corresponding experiment is running (or even exists).

The second bit is accomplished by some code like:
```
condition = getExperimentCondition(point,id);
if (condition == "A")
   doA();
else if (condition == "B")
   doB()
else
   doDefault();
```

The problem is that you might have two versions of the app deployed, both of which have "markExperimentPoint" but only one of which has the conditional. UpGrade doesn't know if the app has the conditional, and the app doesn't know if there is an experiment running. This means that "markExperimentPoint" doesn't tell you whether the student actually experienced the experimental condition. UpGrade might return condition "B" for the student, but the student's going to see the default, if the conditional isn't there. If the two versions are simultaneously deployed, timestamps can't help you.

So we need some way to unambiguously express the semantics that "the app is responding to the assigned condition". I can think of a couple of ways to accomplish this:

1. add a parameter to markExperimentPoint (not great, if the parameter was a boolean saying whether the conditional exists; maybe better if we just pass a version number and somehow know which versions have the conditional)
2. have getExperimentCondition log to UpGrade (which overloads the semantics of that call)
3. add a new API call, to be used within the conditional (or, perhaps, create a new conditional - UpGradeIF, which both does the conditional and logs)
4. somehow collect metadata about what UpGrade-related conditionals exist in the code

**Comment by jerith666** [comment]
I'm only about 75% sure I understand the issue here, but if I do, I don't think it's a problem in my implementation of the `SelectSection` experiment point in Mathia.

In pseudocode, that implementation is roughly this:

```
condition = upgrade.getExperimentCondition("SelectSection", section.getId())

if ( condition == null ) {
    logger.info("no active experiment found for section {}", section);
    return null;
}

try {
    variant = loadVariant(section, condition);
    logger.info("experiment condition for section {}: {}", section, variant);
    upgrade.makeExperimentPoint("SelectSection", section.getId());
    return variant;
} catch (NoSuchVariantException e){
    error = format("experiment condition asks for non-existent variant {} of section {}", variant, section);
    logger.error(error);
    upgrade.failedExperimentPoint("SelectSection", section.getId(), error);
    return null;
}
```

In words, we do not call `markExperimentPoint()` unless UpGrade assigns us to an experimental condition.  Maybe that's not the intent, and we should be calling it even if there is no condition assigned.  But the benefit is that this way, UpGrade knows that it should expect a "reply" in the form of `markExperimentPoint()` (or `failedExperimentPoint()`) iff its response to `getExperimentCondition()` _includes a condition for the current section ID_.

**Comment by SritterCL** [comment]
But part of what markExperimentPoint is supposed to do is tell us whether the user reached the experiment point before the experiment began (so we can exclude). So you should be calling markExperimentPoint, even if there's no experiment.

**Comment by jerith666** [comment]
Ugh, you're right, I wasn't thinking about that at all.

Okay, then I think I'd say we should do a variant of your solution #1: add an argument, but the argument should just be the caller repeating back the condition that's being given to the user.  So updating my pseudo-code from above:

```
--- saps-mep-old        2020-08-28 14:31:28.581528049 -0400
+++ saps-mep-new        2020-08-28 14:32:03.306057396 -0400
@@ -2,13 +2,14 @@
 
 if ( condition == null ) {
     logger.info("no active experiment found for section {}", section);
+    upgrade.markExperimentPoint("SelectSection", section.getId(), null);
     return null;
 }
 
 try {
     variant = loadVariant(section, condition);
     logger.info("experiment condition for section {}: {}", section, variant);
-    upgrade.makeExperimentPoint("SelectSection", section.getId());
+    upgrade.makeExperimentPoint("SelectSection", section.getId(), variant.getId());
     return variant;
 } catch (NoSuchVariantException e){
     error = format("experiment condition asks for non-existent variant {} of section {}", variant, section);
```

(there is no new argument to `failedExperimentPoint()` -- any call to that implies that no variant was given to the student.)

**Comment by SritterCL** [comment]
should we be passing condition to markExperimentPoint, instead of variant.getID? - are those the same thing?

**Comment by jerith666** [comment]
They are the same thing.
