### ISSUE TITLE
Saving when editing an experiment

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/educational-experiment-client#156]
When you edit an experiment, there's a 4-panel dialog. If I change something on the first panel and then click off the dialog, the changes are not saved. I need to go to panel 4 and click "update" in order to save my changes.

If I click off the dialog, I should get a "do you want to save" dialog. Or - I think better - have 3 buttons (cancel, save, next) and don't dismiss the dialog if I click off it.

**Comment by tanmayjain3** [comment]
Hi @SritterCL , we have added "save" button when editing experiment.
