### ISSUE TITLE
Export experiment not working

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/educational-experiment-client#158]
This might be an issue with http://upgrade.qa-cli.net, not UpGrade itself (not sure).

When I hit "export" for an experiment, I get a message saying that the data will be sent to sritter@carnegielearning.com, but I don't get the email. There's nothing in the logs.

**Comment by tanmayjain3** [comment]
Fixed this issue also added logs for successful and unsuccessful export.
