### ISSUE TITLE
UpGrade favicon is Playpower logo

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/educational-experiment-client#170]
Maybe leave this until (if?) Symmetri gives us a more specifically color-oriented logo, but want to note that the favicon is currently the Playpower logo and will need to be changed. Screenshot below. 🙂 

<img width="84" alt="Screen Shot 2020-11-17 at 9 55 35 AM" src="https://user-images.githubusercontent.com/65311369/99406090-80cf5980-28bb-11eb-8056-26a5d781d29d.png">

**Comment by ppratikcr7** [comment]
Does this look good?
![Screenshot 2021-03-10 at 7 46 00 PM](https://user-images.githubusercontent.com/33730817/110642737-4dea0200-81d9-11eb-992a-6f0151ebadf3.png)

**Comment by ppratikcr7** [comment]
Okay. New favicon updated. PR raised for the same.

**Comment by ppratikcr7** [comment]
@amurphy-cl fix is merged, please verify now.

**Comment by ppratikcr7** [comment]
@amurphy-cl Hey, should we close this issue? Or still we need to discuss anything on this?
