### ISSUE TITLE
Link to UpGrade experiment doesn't load experiment dashboard

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/educational-experiment-client#173]
Clicking on a link to an UpGrade experiment dashboard only loads the side pane and not the entire experiment.

Also clicking prompts for authentication even if a user is already logged in.

**Comment by JD2455** [comment]
@amurphy-cl  This is fixed and after clicking Upgrade experiment dashboard, it will load entire experiment along with side pane.
